name: apk
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.3.4 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.6
    email_validator: ^2.0.1
    image_picker: ^1.1.1
    share_plus: ^9.0.0
    shared_preferences: ^2.0.8

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0
    flutter_launcher_icons: ^0.13.1
    flutter_native_splash: ^2.0.7

flutter_icons:
    android: true
    ios: true
    image_path: "assets/images/logo.png"
    adaptive_icon_background: "#ffffff"
    adaptive_icon_foreground: "assets/images/logo.png"

flutter_native_splash:
    color: "#ffffff"
    image: assets/images/logo.png
    android: true
    ios: true
    fullscreen: true

flutter:
    uses-material-design: true
    assets:
        - assets/images/
