name: apk
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.3.4 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.6
    email_validator: ^2.0.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0
    flutter_launcher_icons: ^0.13.1 # This should be under dev_dependencies

flutter:
    uses-material-design: true
    assets:
        - assets/images/twitter.png
        - assets/images/facebook.png
        - assets/images/google.png
        - assets/images/logo.png

flutter_icons: # This block needs to be indented under dev_dependencies
    android: true
    ios: true
    image_path: "assets/images/logo.png"
    adaptive_icon_background: "#ffffff"
    adaptive_icon_foreground: "assets/images/logo.png"
